name: 📊 GitHub Metrics

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Rome
          config_twemoji: yes

          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: all

          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: 2

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_repositories: yes
          plugin_repositories_featured: mxttex/PascalMentor

          plugin_followup: yes
