name: 📈 GitHub Metrics (Languages + Habits)

on:
  schedule:
    - cron: "30 */12 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          config_timezone: Europe/Rome

          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_indepth: yes
          plugin_languages_limit: 8

          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
